package com.example.kasa.ui.screens.auth

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Home
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.kasa.data.repository.KasaRepository
import com.example.kasa.theme.KasaDimens
import com.example.kasa.theme.KasaPrimary

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CreateHouseholdScreen(
    userName: String,
    onHouseholdCreated: () -> Unit,
    onBack: () -> Unit
) {
    var householdName by remember { mutableStateOf("") }
    var selectedCurrency by remember { mutableStateOf("USD") }
    var secondaryCurrency by remember { mutableStateOf("CDF") }
    var exchangeRate by remember { mutableStateOf("2250") }
    var inviteCodeGenerated by remember { mutableStateOf<String?>(null) }

    val currencies = listOf("USD", "EUR", "CDF", "FCFA")
    val isValid = householdName.trim().isNotBlank()

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Créer un foyer", fontWeight = FontWeight.SemiBold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(imageVector = Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Retour")
                    }
                }
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(24.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.SpaceBetween
        ) {
            Column {
                if (inviteCodeGenerated == null) {
                    Text(
                        text = "Configurez votre foyer",
                        style = MaterialTheme.typography.headlineMedium,
                        fontWeight = FontWeight.Bold
                    )
                    Spacer(modifier = Modifier.height(6.dp))
                    Text(
                        text = "Donnez un nom et définissez la devise de gestion.",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )

                    Spacer(modifier = Modifier.height(24.dp))

                    OutlinedTextField(
                        value = householdName,
                        onValueChange = { householdName = it },
                        label = { Text("Nom du foyer") },
                        placeholder = { Text("Ex: Maison Cocody ou Coloc Landry") },
                        leadingIcon = { Icon(Icons.Default.Home, contentDescription = null) },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(KasaDimens.radiusMd)
                    )

                    Spacer(modifier = Modifier.height(16.dp))

                    // Currency Selector
                    Text("Devise principale", style = MaterialTheme.typography.labelLarge)
                    Spacer(modifier = Modifier.height(8.dp))
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        currencies.forEach { curr ->
                            FilterChip(
                                selected = selectedCurrency == curr,
                                onClick = { selectedCurrency = curr },
                                label = { Text(curr, fontWeight = FontWeight.SemiBold) }
                            )
                        }
                    }

                    Spacer(modifier = Modifier.height(16.dp))

                    // Secondary Currency
                    Text("Devise secondaire (optionnel)", style = MaterialTheme.typography.labelLarge)
                    Spacer(modifier = Modifier.height(8.dp))
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        currencies.forEach { curr ->
                            FilterChip(
                                selected = secondaryCurrency == curr,
                                onClick = { secondaryCurrency = curr },
                                label = { Text(curr) }
                            )
                        }
                    }

                    Spacer(modifier = Modifier.height(16.dp))

                    OutlinedTextField(
                        value = exchangeRate,
                        onValueChange = { exchangeRate = it },
                        label = { Text("Taux de change (1 $selectedCurrency = X $secondaryCurrency)") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(KasaDimens.radiusMd)
                    )
                } else {
                    // Success View with Invite Code
                    Column(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        Box(
                            modifier = Modifier
                                .size(80.dp)
                                .background(KasaPrimary.copy(alpha = 0.15f), RoundedCornerShape(24.dp)),
                            contentAlignment = Alignment.Center
                        ) {
                            Text("🎉", fontSize = 40.sp)
                        }

                        Spacer(modifier = Modifier.height(16.dp))

                        Text(
                            text = "Foyer créé avec succès !",
                            style = MaterialTheme.typography.headlineMedium,
                            fontWeight = FontWeight.Bold
                        )

                        Spacer(modifier = Modifier.height(8.dp))

                        Text(
                            text = "Partagez ce code avec les autres membres pour qu'ils rejoignent votre foyer :",
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )

                        Spacer(modifier = Modifier.height(24.dp))

                        Surface(
                            shape = RoundedCornerShape(KasaDimens.radiusLg),
                            color = MaterialTheme.colorScheme.surfaceVariant,
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Column(
                                modifier = Modifier.padding(20.dp),
                                horizontalAlignment = Alignment.CenterHorizontally
                            ) {
                                Text("Code d'invitation", style = MaterialTheme.typography.labelSmall)
                                Spacer(modifier = Modifier.height(4.dp))
                                Text(
                                    text = "UNK-$inviteCodeGenerated",
                                    fontSize = 28.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = KasaPrimary,
                                    letterSpacing = 2.sp
                                )
                            }
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(32.dp))

            Button(
                onClick = {
                    if (inviteCodeGenerated == null) {
                        val hh = KasaRepository.createHousehold(
                            name = householdName.trim(),
                            primaryCurrency = selectedCurrency,
                            secondaryCurrency = secondaryCurrency,
                            exchangeRate = exchangeRate.toDoubleOrNull() ?: 2250.0,
                            userName = userName
                        )
                        inviteCodeGenerated = hh.inviteCode
                    } else {
                        onHouseholdCreated()
                    }
                },
                enabled = isValid,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(54.dp),
                shape = RoundedCornerShape(KasaDimens.radiusMd),
                colors = ButtonDefaults.buttonColors(containerColor = KasaPrimary)
            ) {
                Text(
                    text = if (inviteCodeGenerated == null) "Créer le foyer" else "Accéder au tableau de bord",
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = Color.White
                )
            }
        }
    }
}
